### PR TITLE
Epitable 20230727

### PR DESCRIPTION
**Pull request by epi-jhd**
Edits have been made to: 
epitable()
outputtable()
tab_row()

a) all combinations of true and false inputs for col, row, total and missing now work
b) I have added an option 'tout' to epitable (I know, this is not good, but all other iterations of total were taken, suggestions welcome) that enables you to output a table or percentages from the whole data (as opposed to by row or column as present)
c) I have added an option 'totperc' to outputable - when true this means the total percentages are displayed, with a 'O' as indice
d) I have added an option 'perc' to tab_row that when true puts the percentage type indice at the end of the row when total column is absent.

### CODE REVIEW

**Comment by epi-gde** [comment]
Perfect Job ! (and this one was not easy !) 
I added some example and improved the help which was very old (I also added the new param for percentages)
tout param was changed into perc  (row and col could be viewed as rowperc and colperc, may be we can change name ?)
O indicator was changed to X which is more consistent with > and V 
And finally merged with main to check CRAN compatibility

**Review by epi-gde — APPROVED** [review]

**Review by epi-gde — APPROVED** [review]
Parfait pour moi ;)

**Review by loremerdrignac — APPROVED** [review]
Thank you!
I have just added tiny minor suggestions to the doc of epitable.
Next step is the merging to the main! :)

**Comment by epi-gde** [comment]
Last minor changes, I added in roxygen the totperc option to get percentage/total
(Was working but not visble in the code completion feature)

**Pull request merged**
