### PR TITLE
API suggestions

### PR DESCRIPTION
**Pull request by loremerdrignac**
Dear @EPI-JHS and @epi-gde,
I hope you are well and had a wonderful Christmas!
I had a quick look at the APIs functions and wanted to suggest you some minor modifications that I made in the following branch: APIs_suggestions. 
The main suggestion is to remove the printed messages in the console and replace them with message(), warning() or stop() messages. I hope this is fine by you! Please note that I have adapted the tests accordingly.
Additionally, I was wondering if, when creating a kearing in createKeyring(), printing the password in the console was necessary or if we should omit this output.
Please let me know your thoughts!
Best wishes,
Lore

### CODE REVIEW

**Comment by EPI-JHS** [comment]
Hello again @loremerdrignac, I've tested each of the functions in Keyring.r and also the downloadREDCap() function - all work perfectly. Thank you again for your help!

**Review by EPI-JHS — APPROVED** [review]
Tested all functions, no errors or issues and data downloaded as expected

**Comment by loremerdrignac** [comment]
Dear both!
Sorry I forgot to add a comment following our last exchangeon 4-5th January :)
Since your first review James, I added more (but still minor) suggestions to the current branch to remove the API secret print call. I replaced it with simple messages. 
Let me know if this is fine by you!

**Review by EPI-JHS — COMMENTED** [review]
Thank you for making these changes, they all look great to me!

**Review by epi-gde — APPROVED** [review]
Perfect, nothing to add ;)

**Pull request merged**
