### PR TITLE
Improve fillimage() function

### PR DESCRIPTION
**Pull request by epi-mml**
Add the possibility to insert an image from the R environment to the Excel file using the openXlsx::insertPlot() function

### CODE REVIEW

**Comment by epi-gde** [comment]
Few comment/help added to fillimage function, vignette example added
Ready for pull request

**Comment by loremerdrignac** [comment]
Few comments on my side too :)
Could we use this opportunity to rename in camelCase fillimage into fillImage so that it is consistent with the other epiuf function?
Let me know your thoughts!

**Comment by epi-gde** [comment]
> Could we use this opportunity to rename in camelCase fillimage into fillImage so that it is consistent with the other epiuf function?

Yes I think  I have started with that but fillImage is not easy to read :(  what about pasteImage ?

**Comment by loremerdrignac** [comment]
I was also thinking of "**addImage**" maybe more meaningful?
I initially tried to keep fillimage as obsolete because the only difference between the two functions is the case, it could not work... If we change the name, then we can keep it as obsolete! :)

**Pull request merged**
