### PR TITLE
Apply dictionary 2023 09 18

### PR DESCRIPTION
**Pull request by epi-clz**
Hi girls! 
Thank you so much for reviewing. 
I have made changes in the following functions: 
openDictionary()
applyDictionary()
compareDataset()
I have noted that with ## PR_CLZ and ##END_PR_CLZ
Let me know if anything is unclear or you need help

### CODE REVIEW

**Comment by epi-jhd** [comment]
Comments after testing the openDictionary() function (all other changes look great! ) 

- Do any dictionary functions interact with the comments column?  -> if not, suggest ignoring this column if present
- Extra sheets in the dictionary causes a warning -> suggest ignoring extra sheets if the main three are present (Sometimes it is useful to have extra reference sheets in dictionaries -not to use in R, but to keep useful information all in one place)
- When one of the sheets is totally empty, there is no warning or explanation -> suggest creating the columns and inform that have done so.

**Comment by epi-gde** [comment]
I agree with Jenny, no warning is necessary if we have extra sheet  or extra column  as long we don't use them for dictionary

**Comment by epi-clz** [comment]
Hi all. In order go through Jenny's suggestions I'd like to share the workflow of the function now:

1. Check if the essential sheets are found in the excel. Otherwise print warning.
2. If Ok, check if all sheet are not completely blank. Otherwise print warning.
3. If Ok, check if any of the sheets lacks of any essential column. Otherwise print warning and creates automatically the cols as blank.

If everything Ok -> runs the function with no problems
If necessary, adds cols missing in the current user dictionary as blank, warning the user with a message.
@epi-jhd @epi-gde @loremerdrignac

**Comment by epi-jhd** [comment]
Had a check and it's working like a dream :)

**Review by epi-gde — COMMENTED** [review]
May be to avoid repeat and to simplify the main fonction ?
And to limit the if imbrication in the main code ?

Just inserting a function like this one ? (To be completed )
function checkDicoSheet( FieldList,SheetName)
{
sheet1 <- readData(filename, sheet = "dictionary",verbose = F) # sheet dictionary
if(all(is.na(sheet1) warning("Sheet ",SheetName," completely blank")
if(!all(FieldList%in%names(sheet1))){ warning("Sheet 'dictionary' not correct: ",addSep(FieldList, ",") ," cols needed.") }
}

We can review this together ;)

**Comment by epi-mml** [comment]
It works very well , well done Cris :)!
I just have an idea/suggestion: do you think it can be useful to precise the missing sheet ? (For example, if the "actions" sheet doesn't exist, print "Sheet in XXX : actions sheets is missing".

**Review by epi-jhd — APPROVED** [review]
Warnings all acting as planned
Thanks Cris! :)

**Review by epi-mml — APPROVED** [review]
It works very well, thanks Cris!

**Review by epi-gde — APPROVED** [review]

**Pull request merged**
