### PR TITLE
REDCap API access functions

### PR DESCRIPTION
**Pull request by epi-gde**
Three separate functions with roxygen formatting (*not yet built*) allowing users to 1) set/retrieve API secrets (createOrUpdateKeyring.R) 2) access REDCap after searching for a stored secret using a country code of interest (accessREDCap.R), and 3) download REDCap data relating to the country of interest using the retrieved secret or by supplying the secret in directly in the call to the function (downloadREDCap.R).

### CODE REVIEW

**Comment by epi-gde** [comment]
We may also pass some parameters for the csv file knowing that sep may changes across platform/language and finally the function could return the file name  in order to  chain the process.

**Comment by EPI-JHS** [comment]
Apologies - missed this thread. Have now subscribed, and will work on the suggestions

**Comment by EPI-JHS** [comment]
I've found some issues with the original functions. Have updated these for my specific purpose, and will now work on generalising once more. 

Also, I have created an additional function ("UpdateOrDeleteKey") allowing users to directly delete a key or, instead, change it's secret - will also submit this once ready.


@epi-gde: Instead of prompting the user or setting the file path through passing a setpath in each function call - what do you think about this:

- When a user creates a new key as part of the accessredcap() flow, we store the distinct parent folder path for that country/project (either in the func call, or as prompted) next to the keyring password. In this way the user is asked just once for that path, and it is stored alongside the API secret in the user's OS credential list, to be grabbed with the API key on the next request.

**Comment by epi-gde** [comment]
Hi James, storing path along with the keyring password is a good idea. 
It would be perfect if the function could manage either a full path or a relative setpath() keywword,  setpath advantage is the possibility to move the entire project (when you duplicate the project for some test, or when a colleague install the project on his computer to test it ... etc 
Let us know if you want some infos about setpath()/getpath()  fucntions ;) 

And UpdateOrDeleteKey is also great idea !

**Comment by EPI-JHS** [comment]
Fantastic - I agree, a relative setPath() pre-set by the user, suffixed with: the country + date + time (e.g., for looping over several countries as I do below). 

For reference, I am pasting below my working solution that is yet to be generalised:




#### Must update general function to take a list of countries
``` R
global$COUNTRYLIST <- c("CA", "CB","CC", "CD", "CE")

accessREDCap(global$COUNTRYLIST)
```

#### As below, must also account for single-country additions
``` R
accessREDCap <- function(countryList) {
  for(country in countryList){
    password <- CreateOrGrabKeyring(country)
    downloadRedCap(password,country)
  }
}
```

#### Few changes, except now sets Today's date (as year and month) upfront for file path. This must be updated to allow dynamic file path setting. The part that's useful to me, hardcoded, is "/WHOAFROMoVECOVDI19VE_DATA_". Need to find a way to generalise this part (likely using setPath(), per GDE suggestion).
``` R
downloadRedCap <- function(password,country) {
  yearDate <- format(Sys.Date(), "%Y")
  month_number <- format(Sys.Date(), "%m")
  # The URL we are requesting data from
  url <- "https://extranet.who.int/edcrc/api/"
  
  # Parameters for the request
  formData <- list(token=password,
                   content='record',
                   action='export',
                   format='csv',
                   type='flat',
                   csvDelimiter='',
                   rawOrLabel='raw',
                   rawOrLabelHeaders='raw',
                   exportCheckboxLabel='true',
                   exportSurveyFields='true',
                   exportDataAccessGroups='true',
                   returnFormat='csv'
  )
  
  # Make the request using httr and POST method
  response <- httr::POST(url, body = formData, encode = "form")
  
  # Convert the httr response content and assign it to the name 'REDCapExtract'
  REDCapExtract <- httr::content(response)
  print(REDCapExtract)
  
  # Prompt user for the file path within which they'd like to save the file
  dataLocation <- pathToFile("SOURCES", paste0(country,"/", yearDate ," ", month_number))
  fileName <- paste0(dataLocation,"/WHOAFROMoVECOVDI19VE_DATA_",Sys.Date(),"_",strftime(Sys.time(), "%H%M"),".csv")
  
  # Download the r dataframe to CSV
  write.csv(REDCapExtract, fileName, row.names=FALSE)
}
```

#### Name change, change in functionality to account for windows OS credential system quirks
``` R
CreateOrGrabKeyring <- function(keyring_id) {
  key_id <- paste0(keyring_id,"_keyring")
  if(key_id %in% keyring::keyring_list()$keyring) {
    password <- keyring::key_get(keyring_id, keyring = key_id)
  } else {
    print("Keyring not found. Beginning the process of creating a new keyring starting with the API secret value to be stored.")
    passcode <- readline("Enter the API key/secret to be stored: ")
    keyring::keyring_create(key_id,password = passcode)
    keyring::key_set_with_value(keyring_id, keyring = key_id,password = passcode)
    password <- keyring::key_get(keyring_id, keyring = key_id)
  }
  return(password)
}
```

#### New function for deleting or updating secret of key (actually deletes and recreates, hidden from user)
``` R
UpdateOrDeleteKeyring <- function(keyring_id) {
  key_id <- paste0(keyring_id,"_keyring")
  if(key_id %in% keyring::keyring_list()$keyring) {
    answer <- readline("The keyring record has been found. Type *D*elete to delete the key, or *U*pdate to update the secret.")
    if(tolower(answer)=="d"|tolower(answer)=="delete"){
      print("Deleting - When prompted, type yes")
      keyring::keyring_delete(key_id)
      print("Secret deleted")
    } else if(tolower(answer)=="u"|tolower(answer)=="update"){
      print("Updating - When prompted, type yes")
      keyring::keyring_delete(key_id)
      passcode <- readline("Enter the new API key/secret to be stored: ")
      keyring::keyring_create(key_id,password = passcode)
      keyring::key_set_with_value(keyring_id, keyring = key_id,password = passcode)
      print("Secret Updated")
    } else {
      print("Answer unclear, please run again")
    }
  } else {
    print("That keyring wasn't found. Run CreateOrGrabKeyring() to set a new secret")
  }
}
```

**Comment by EPI-JHS** [comment]
Adding to tasks - likely begin working on generalised function 1st Dec

**Comment by EPI-JHS** [comment]
*Functions to be updated within this branch before merging back to main*

**Comment by EPI-JHS** [comment]
I've had a moment to update and test the create and update keyrings functions:

#### CreateOrGrabKeyring()

- Might only work on Windows OS
- Takes a 'keyring_id' in the call (e.g., the name of a country or project)
- Checks the user's windows credential manager for a key with that id
- If no existing one is found it will request a memorable 4 digit pin. This pin is for locking and unlocking the windows password manager and retrieving the secret. If an acceptable 4 digit pin is entered, will then request the actual secret to be stored (e.g., API key). 
- If the keyring_id is a match for an existing credential manager entry, it will request the 4 digit pin set upon creation, which unlocks and returns the password 

``` R
CreateOrGrabKeyring <- function(keyring_id) {
  key_id <- paste0(keyring_id,"_keyring")
  if(key_id %in% keyring::keyring_list()$keyring) {
    print("If you receive a prompt suggesting the key is locked, enter your 4 digit passcode to unlock it first.")
    password <- keyring::key_get(keyring_id, keyring = key_id)
  } else {
    print("Keyring not found. Beginning the process of creating a new keyring starting with the API secret value to be stored.")
    passcode <- readline("Enter a memorable 4 digit numeric pin to lock this secret: ")
    if(nchar(passcode)==4&!is.na(passcode)){
      secret <- readline("Enter the actual API key/secret to be stored: ")
      keyring::keyring_create(key_id,password = passcode)
      keyring::key_set_with_value(keyring_id, keyring = key_id,password = secret)
      password <- keyring::key_get(keyring_id, keyring = key_id)
    } else {
      print("Passcode is not 4 numeric digits, starting again.")
      CreateOrGrabKeyring(keyring_id)
    }
  }
  return(password)
}
```

#### UpdateOrDeleteKeyring()

- Much like the above, though it checks that the keyring_id exists then, if it does, it asks whether they would like to update or delete the key
- On Update, a final prompt asks if the user is sure (if the key has secrets within it), then it deletes the keyring and runs the create function thereafter, passing the original keyring_id in the call
- On Delete, it is simply deleted - a final prompt asks the user if they're sure

``` R
UpdateOrDeleteKeyring <- function(keyring_id) {
  key_id <- paste0(keyring_id,"_keyring")
  if(key_id %in% keyring::keyring_list()$keyring) {
    answer <- readline("The keyring record has been found. Type *D*elete to delete the key, or *U*pdate to update the secret.")
    if(tolower(answer)=="d"|tolower(answer)=="delete"){
      print("Deleting - When prompted, type yes")
      keyring::keyring_delete(key_id)
      print("Secret deleted")
    } else if(tolower(answer)=="u"|tolower(answer)=="update"){
      print("Updating - When prompted, type yes")
      keyring::keyring_delete(key_id)
      CreateOrGrabKeyring(keyring_id)
    } else {
      print("Answer unclear, write *D*elete or *U*pdate only. Starting again")
      UpdateOrDeleteKeyring(keyring_id)
    }
  } else {
    print("That keyring wasn't found. Would you like to create a new keyring? Type (Y)es or (N)o.")
    CreateOrGrabKeyring(keyring_id)
  }
}
```

**Comment by EPI-JHS** [comment]
These are functioning, though the next step now is to add another function allowing easy storage and retrieval of the file path when using these function to download REDCap and data from other API endpoints

- Must be stored relative to the keyring_id, so that when the user asks for a specific REDCap project, the filepath is automatically retrieved and used to file the data

**Comment by EPI-JHS** [comment]
Adding further functionality for file paths when downloading REDCap data via API:

#### accessREDCap

- The function for checking whether a secret exists, checking that a file path for that secret's output exists, and then directing both to the download redcap function
- If a secret or filepath aren't set, it will direct the user to create these. Alternatively, they can make do with just the secret, though the downloadredcap function will just place the downloaded file in their working directory

``` R
accessREDCap <- function(country) {
  password <- CreateOrGrabKeyring(country)
  
  country_filepathfull <- paste0(country,"_pathkeyfull")
  country_filepathpartial <- paste0(country,"_pathkeypart")
  
  if(country_filepathfull %in% keyring::keyring_list()$keyring){
    country_filepath <- country_filepathfull
    keyring::keyring_unlock(keyring = country_filepath, password = country)
    file_path <- keyring::key_get(country, keyring = country_filepath)
    
    downloadRedCap(password,country,file_path)
    
  } else if(country_filepathpartial %in% keyring::keyring_list()$keyring){
    country_filepath <- country_filepathpartial
    yearDate <- format(Sys.Date(), "%Y")
    month_number <- format(Sys.Date(), "%m")
    
    keyring::keyring_unlock(keyring = country_filepath, password = country)
    file_path <- keyring::key_get(country, keyring = country_filepath)
    file_path <- pathToFile("SOURCES", paste0(file_path,"/", yearDate ," ", month_number))
    
    downloadRedCap(password,country,file_path)
    
  } else {
    print("A file path, within which the downloaded data will be placed, has not been set for this country yet.") 
    store_file <- readline("Would you like to set one now? It may save time in future. Type (Y)es or (N)o.")
    if(tolower(store_file)=="y"|tolower(store_file)=="yes"){
      setOrGetFilePath(country)
      accessREDCap(country)
    } else {
      downloadRedCap(password,country)
    }
  }
}
```

#### setOrGetFilePath

- Asks the user several questions before setting a secret (in the same way as CreateOrGrabKeyring), the ID for which is exactly the same as the ID for the API secret, except with the suffix "_keypath".
- Gives 3 options for file paths currently, based on anticipated filing practices (all in one folder, split by country, or split by country and month)

``` R
setOrGetFilePath <- function(country){
  
  print("Setting the file path can be done in several ways, depending on your project filing practices:") 
  print("1) These data always go to the exact same folder (e.g., my_files/sources)")
  print("2) Data are separated by country name within a shared parent folder (e.g., my_files/sources/spain)")
  print("3) Data are separated by country name AND date of download, within a shared parent folder (e.g., my_files/sources/spain/2023 11)")
  
  file_procedure <- readline("Type which of 1, 2, or 3 best describes your filing practices:")
  
  if(file_procedure == 1){
    file_path <- readline("Paste the full file path either as ID (must already be set with setPath(), e.g., 'SOURCES') or copy paste the full filepath whole:")
    if(!is.null(getPath(file_path))){
      file_path <- getPath(file_path)
    } else {
      print("found no setPath() call, assuming whole file path copy pasted")
    }
  } else if(file_procedure == 2| file_procedure == 3){
    file_path <- readline("Paste the full PARENT folder path either as ID (must already be set with setPath(), e.g., SOURCES) or
                          copy paste the full filepath whole:")
    if(!is.null(getPath(file_path))){
      file_path <- getPath(file_path)
      file_path <- paste0(file_path,country,"/")
    } else {
      print("found no setPath() call, assuming whole file path copy pasted")
      file_path <- paste0(file_path,"/",country,"/")
    }
    
  } else {
    print("Unrecognised input")
  }
  
  print(paste("Does this look like the correct filepath?",file_path))
  answer <- readline("(Y)es, (N)o:")
  
  if(tolower(answer)=="n"|tolower(answer)=="no"){
    print("Starting again.")
  } else {
    if(file_procedure == 1 | file_procedure == 2){
      countrypath_key <- paste0(country,"_pathkeyfull")
    } else if(file_procedure == 3){
      countrypath_key <- paste0(country,"_pathkeypart")
    }
    keyring::keyring_create(countrypath_key,password = country)
    keyring::key_set_with_value(country, keyring = countrypath_key,password = file_path)
    file_path <- keyring::key_get(country, keyring = countrypath_key)
  } 
}
```

#### downloadRedCap
- Makes the API call using the secrets and file paths set by accessREDCap()

``` R
downloadRedCap <- function(password,country,file_path=NULL) {
  yearDate <- format(Sys.Date(), "%Y")
  month_number <- format(Sys.Date(), "%m")
  # The URL we are requesting data from
  url <- "https://extranet.who.int/edcrc/api/"
  
  # Parameters for the request
  formData <- list(token=password,
                   content='record',
                   action='export',
                   format='csv',
                   type='flat',
                   csvDelimiter='',
                   rawOrLabel='raw',
                   rawOrLabelHeaders='raw',
                   exportCheckboxLabel='true',
                   exportSurveyFields='true',
                   exportDataAccessGroups='true',
                   returnFormat='csv'
  )
  
  # Make the request using httr and POST method
  response <- httr::POST(url, body = formData, encode = "form")
  
  # Convert the httr response content and assign it to the name 'REDCapExtract'
  REDCapExtract <- httr::content(response)
  print(REDCapExtract)
  
  # Prompt user for the file path within which they'd like to save the file
  if(is.null(file_path)){
    file_name <- paste0(country,"_",Sys.Date(),"_",strftime(Sys.time(), "%H%M"),".csv")
    location <- paste0(getwd(),"/",file_name)
    print("No file path set. Saving in working directory:")
    print(location)
  } else {
    file_name <- paste0(country,"_",Sys.Date(),"_",strftime(Sys.time(), "%H%M"),".csv")
    location <- paste0(file_path,file_name)
  }
  
  # Download the r dataframe to CSV
  write.csv(REDCapExtract, location, row.names=FALSE)
  
  print(paste("File downloaded:", location))
}
```

**Comment by EPI-JHS** [comment]
@epi-gde @loremerdrignac 

All REDCap and keyring functions updated & committed, please let me know if I can change/adapt anything!

**Comment by epi-gde** [comment]
Look good ! Any Dummy redcap access to test functions ?
(You mention earlier that it could not work on Apple ? I woul be happy to test that )

**Comment by EPI-JHS** [comment]
That'd be great, thanks! 

All API endpoints open to me are for real project data right now, though I've gotten in touch with my colleague who has the privileges necessary to create projects and asked for a dummy project + endpoint for testing. I'll share access if/when received!

For testing Mac compatibility, though, we don't strictly require a key just yet. The steps required to test the key functionality;

1. CreateOrGrabKeyring("TEST"), should return "Key not found..." 
2. Enter the secret to store (this will be the API key itself), for now e.g., "TESTSECRET"
3. If successful, outputs string: "TESTSECRET" - key is stored. 
4. To grab the key, again type CreateOrGrabKeyring("TEST"). If successful, should again output "TESTSECRET" - this is the Grab part of the function

To test updating the key, type UpdateOrDeleteKeyring("TEST")

To test setting a file path, type setOrGetFilePath("TEST")

Only accessRedcap and downloadRedcap really require REDCap access - the others I have attempted to generalise such that they may be used to store keys/file paths in your credential manager for other purposes besides

**Comment by epi-gde** [comment]
Detail : when calling UpdateOrDeleteKeyring("WRONG"), you have a message with a choice but no choice ... and it ask for a key, then if you enter a Key secret you get an error. (because you try to add a key secret to  invalid keyring) 
I don't know others opinion, but i usually avoid waiting for responds from functions (except for the key of course ! )
UpdateOrDeleteKeyring("TEST") could just issue a message and return NA if no key exist
then users can test that in there script 
Doing that we will also be able to add test to that function ;)
Would you mind if we create 2 functions ? updateKeyring and deleteKeyring because they are really different actions ;) 
Trying to create a key, I got an error "passcode" not found, it should be secret right ? 

Would you like me to create tests for this function ?

**Comment by EPI-JHS** [comment]
I see your thinking - especially the need to reduce user input to increase utility of the function inside existing scripts... What do you think of the below;


#### CheckKeyringExists
``` R
CheckKeyringExists <- function(keyring_id) {
  key_id <- paste0(keyring_id,"_keyring")
  if(key_id %in% keyring::keyring_list()$keyring) {
    print("Keyring exists")
    return(TRUE)
  } else {
    return(NA)
  }
}
```

#### UpdateKeyring
``` R
UpdateKeyring <- function(keyring_id) {
  key_id <- paste0(keyring_id,"_keyring")
  if(key_id %in% keyring::keyring_list()$keyring) {
      print("Updating - When prompted, type yes")
      keyring::keyring_delete(key_id)
      CreateOrGrabKeyring(keyring_id)
  } else {
    print("That keyring wasn't found - let's create a new one")
    CreateOrGrabKeyring(keyring_id)
  }
}
```

#### DeleteKeyring
``` R
DeleteKeyring <- function(keyring_id) {
  key_id <- paste0(keyring_id,"_keyring")
  if(key_id %in% keyring::keyring_list()$keyring) {
    print("Deleting - When prompted, type yes")
    keyring::keyring_delete(key_id)
    print("Secret deleted")
  } else {
    print("That keyring wasn't found.")
  }
}
```

#### Regarding issues found:

- My apologies! I pushed an older version of the create or grab function that still requested a passcode.. I've just rectified it, and you should now be able to test this function properly.

**Comment by EPI-JHS** [comment]
Tested the new and improved functions using real REDCap project data and can confirm that the keyrings are stored/retrieved as expected, and that data successfully download.

Now focusing on the filepath issue that remains with downloadRedCap() - adding to 2024 tasks!

**Pull request merged**
