### PR TITLE
55 dictionary slow applynaall

### PR DESCRIPTION
**Pull request by epi-gde**
Full test has been added (thanks to the vignette ! I just have to copy-past) 
Then code was profiled to identify long process (mainly repetitive grep ) and then simplified while using faster method  
Code is 40 times faster for apply NA and hundred time faster for checkDico

Notice that 
- applyNA work only on full content, should we check for words ?
- checkDico only works with numeric dico, should we extend to character ?

### CODE REVIEW

**Comment by epi-gde** [comment]
MatchDico works for character dico (put NA if not valid , doesn't count or print !)  , should be harmonised with checkDico

**Comment by epi-gde** [comment]
expandVar and expandVarAll corrected , test added and vignette updated 
genericdisctionary.xlsx added for testing dictionary function on a xlsx file

**Comment by epi-gde** [comment]
All issues are reviewed, pull request ok

**Review by epi-jhd — APPROVED** [review]
applyNAAll, checkDicoAll, expandVarAll, collapseVarAll and getAnyDictionaryValue tested in 'real life' setting and they function as expected. 
(or much faster for applyNAAll and checkDicoAll)

**Pull request merged**
